services:

  postgres:
    image: postgres:16
    container_name: cabinet_postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - postgres_data:/var/lib/postgresql/data


  airflow:
    build:
      context: .
      dockerfile: Dockerfile

    image: cabinet-airflow:3.3.1

    container_name: cabinet_airflow

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt

    command: standalone


volumes:
  postgres_data: